name: 'build, test'
description: 'composite actions'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore
      shell: bash
    - name: Build
      run: dotnet build
      shell: bash
    - name: Test with the dotnet CLI
      run: dotnet test
      shell: bash
