name: 'build, test'
description: 'composite actions'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore
      shell: bash
    - name: Build
      run: dotnet build
      shell: bash
    - name: Test with the dotnet CLI
      run: dotnet test "trx;LogFileName=test-results.trx" || true
      shell: bash
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.0.2
      with:
        filename: coverage/index/coverage.cobertura.xml # double check path with targetdir parameter above
        badge: true
        format: 'markdown'
        output: 'both'
