name: 'build, test'
description: 'composite actions'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore
      shell: bash
    - name: Build
      run: dotnet build
      shell: bash
    - name: Test with the dotnet CLI
      run: dotnet test
      shell: bash
    - name: Copy Coverage To Predictable Location
      run: cp coverage/*/coverage.cobertura.xml coverage/coverage.cobertura.xml
      shell: bash
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.4
      with:
        reports: 'coverage/*/coverage.cobertura.xml' # REQUIRED # The coverage reports that should be parsed (separated by semicolon). Globbing is supported.
        targetdir: 'coveragereport' # REQUIRED # The directory where the generated report should be saved.
        reporttypes: 'HtmlInline;Cobertura' # The output formats and scope (separated by semicolon)

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.0.2
      with:
        filename: coveragereport/coverage.cobertura.xml # double check path with targetdir parameter above
        badge: true
        format: 'markdown'
        output: 'both'
